"""lot10_audit_logs_gdpr

Revision ID: 54ffcbb7ee60
Revises: 951be1c54f01
Create Date: 2025-12-04 22:34:40.306141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54ffcbb7ee60'
down_revision: Union[str, Sequence[str], None] = '951be1c54f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('level', sa.String(length=20), nullable=False, comment='Log level: debug, info, warning, error, critical'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='API endpoint path'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='HTTP method'),
    sa.Column('request_id', sa.String(length=36), nullable=True, comment='Unique request ID'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User performing the action'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant context'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client user agent'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request duration in milliseconds'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional structured data (headers, params, etc.)'),
    sa.Column('action', sa.String(length=100), nullable=True, comment='Action category: auth, sync, analysis, gdpr, etc.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['optimizer.tenant_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['optimizer.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='optimizer'
    )
    op.create_index(op.f('ix_optimizer_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_endpoint'), 'audit_logs', ['endpoint'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_level'), 'audit_logs', ['level'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_response_status'), 'audit_logs', ['response_status'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='optimizer')
    op.alter_column('addon_compatibility', 'service_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Service type (e.g., 'Microsoft 365', 'Dynamics 365')",
               existing_comment='Service type (e.g., "Microsoft 365", "Dynamics 365")',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'addon_category',
               existing_type=sa.VARCHAR(length=100),
               comment="Category of add-on (e.g., 'Storage', 'Calling Plan')",
               existing_comment='Category of add-on (e.g., "Storage", "Calling Plan")',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'min_quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Minimum quantity required',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'quantity_multiplier',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Quantity must be multiple of this value',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'requires_domain_validation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Requires domain-level validation',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'requires_tenant_validation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Requires tenant-level validation',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Whether this mapping is active',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'effective_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Date when this mapping becomes effective',
               existing_nullable=True)
    op.alter_column('addon_compatibility', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Date when this mapping expires',
               existing_nullable=True)
    op.alter_column('addon_compatibility', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('analyses', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='analysis_status'),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='analysis_status', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('analyses_tenant_client_id_fkey', 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('analytics_metrics', 'metric_type',
               existing_type=postgresql.ENUM('license_utilization', 'license_cost', 'license_savings', 'license_efficiency', 'active_users', 'inactive_users', 'disabled_users', 'guest_users', 'exchange_usage', 'sharepoint_usage', 'teams_usage', 'onedrive_usage', 'mfa_coverage', 'risk_score', 'compliance_score', name='metric_type'),
               type_=postgresql.ENUM('license_utilization', 'license_cost', 'license_savings', 'license_efficiency', 'active_users', 'inactive_users', 'disabled_users', 'guest_users', 'exchange_usage', 'sharepoint_usage', 'teams_usage', 'onedrive_usage', 'mfa_coverage', 'risk_score', 'compliance_score', name='metric_type', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('analytics_metrics_tenant_client_id_fkey', 'analytics_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_metrics', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('analytics_snapshots', 'snapshot_type',
               existing_type=postgresql.ENUM('license_inventory', 'user_inventory', 'service_usage', 'security_status', 'cost_analysis', 'optimization_recommendations', name='snapshot_type'),
               type_=postgresql.ENUM('license_inventory', 'user_inventory', 'service_usage', 'security_status', 'cost_analysis', 'optimization_recommendations', name='snapshot_type', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('analytics_snapshots_tenant_client_id_fkey', 'analytics_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'analytics_snapshots', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('license_assignments', 'status',
               existing_type=postgresql.ENUM('active', 'suspended', 'disabled', 'trial', name='license_status'),
               type_=sa.Enum('active', 'suspended', 'disabled', 'trial', name='license_status', schema='optimizer'),
               existing_nullable=False)
    op.alter_column('license_assignments', 'source',
               existing_type=postgresql.ENUM('manual', 'auto', 'group_policy', name='assignment_source'),
               type_=sa.Enum('manual', 'auto', 'group_policy', name='assignment_source', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('license_assignments_user_id_fkey', 'license_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'license_assignments', 'users', ['user_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('microsoft_prices', 'segment',
               existing_type=postgresql.ENUM('Commercial', 'Education', 'Charity', name='pricing_segment'),
               type_=sa.Enum('Commercial', 'Education', 'Charity', name='pricing_segment', schema='optimizer'),
               existing_nullable=False)
    op.alter_column('microsoft_prices', 'billing_plan',
               existing_type=postgresql.ENUM('Annual', 'Monthly', name='billing_plan'),
               type_=sa.Enum('Annual', 'Monthly', name='billing_plan', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('microsoft_prices_product_id_sku_id_fkey', 'microsoft_prices', type_='foreignkey')
    op.create_foreign_key(None, 'microsoft_prices', 'microsoft_products', ['product_id', 'sku_id'], ['product_id', 'sku_id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('recommendations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('recommendations_user_id_fkey', 'recommendations', type_='foreignkey')
    op.drop_constraint('recommendations_analysis_id_fkey', 'recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'recommendations', 'analyses', ['analysis_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.create_index(op.f('ix_optimizer_reports_created_at'), 'reports', ['created_at'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_reports_expires_at'), 'reports', ['expires_at'], unique=False, schema='optimizer')
    op.create_index(op.f('ix_optimizer_reports_report_type'), 'reports', ['report_type'], unique=False, schema='optimizer')
    op.drop_constraint('reports_tenant_client_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_analysis_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.create_foreign_key(None, 'reports', 'analyses', ['analysis_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.alter_column('tenant_app_registrations', 'consent_status',
               existing_type=postgresql.ENUM('pending', 'granted', 'revoked', 'expired', name='consent_status'),
               type_=postgresql.ENUM('pending', 'granted', 'expired', 'revoked', name='consent_status', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('tenant_app_registrations_tenant_client_id_fkey', 'tenant_app_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_app_registrations', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.add_column('tenant_clients', sa.Column('gdpr_consent', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='GDPR consent given'))
    op.add_column('tenant_clients', sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True, comment='Date of GDPR consent'))
    op.alter_column('tenant_clients', 'onboarding_status',
               existing_type=postgresql.ENUM('pending', 'active', 'suspended', 'error', name='onboarding_status'),
               type_=postgresql.ENUM('pending', 'active', 'suspended', 'error', name='onboarding_status', schema='optimizer'),
               existing_nullable=False)
    op.drop_constraint('usage_metrics_user_id_fkey', 'usage_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'usage_metrics', 'users', ['user_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    op.drop_constraint('users_tenant_client_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenant_clients', ['tenant_client_id'], ['id'], source_schema='optimizer', referent_schema='optimizer', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('users_tenant_client_id_fkey', 'users', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'usage_metrics', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('usage_metrics_user_id_fkey', 'usage_metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenant_clients', 'onboarding_status',
               existing_type=postgresql.ENUM('pending', 'active', 'suspended', 'error', name='onboarding_status', schema='optimizer'),
               type_=postgresql.ENUM('pending', 'active', 'suspended', 'error', name='onboarding_status'),
               existing_nullable=False)
    op.drop_column('tenant_clients', 'gdpr_consent_date')
    op.drop_column('tenant_clients', 'gdpr_consent')
    op.drop_constraint(None, 'tenant_app_registrations', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('tenant_app_registrations_tenant_client_id_fkey', 'tenant_app_registrations', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenant_app_registrations', 'consent_status',
               existing_type=postgresql.ENUM('pending', 'granted', 'expired', 'revoked', name='consent_status', schema='optimizer'),
               type_=postgresql.ENUM('pending', 'granted', 'revoked', 'expired', name='consent_status'),
               existing_nullable=False)
    op.drop_constraint(None, 'reports', schema='optimizer', type_='foreignkey')
    op.drop_constraint(None, 'reports', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('reports_analysis_id_fkey', 'reports', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('reports_tenant_client_id_fkey', 'reports', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_optimizer_reports_report_type'), table_name='reports', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_reports_expires_at'), table_name='reports', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_reports_created_at'), table_name='reports', schema='optimizer')
    op.drop_constraint(None, 'recommendations', schema='optimizer', type_='foreignkey')
    op.drop_constraint(None, 'recommendations', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('recommendations_analysis_id_fkey', 'recommendations', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('recommendations_user_id_fkey', 'recommendations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recommendations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status', schema='optimizer'),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='recommendation_status'),
               existing_nullable=False)
    op.drop_constraint(None, 'microsoft_prices', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('microsoft_prices_product_id_sku_id_fkey', 'microsoft_prices', 'microsoft_products', ['product_id', 'sku_id'], ['product_id', 'sku_id'], ondelete='CASCADE')
    op.alter_column('microsoft_prices', 'billing_plan',
               existing_type=sa.Enum('Annual', 'Monthly', name='billing_plan', schema='optimizer'),
               type_=postgresql.ENUM('Annual', 'Monthly', name='billing_plan'),
               existing_nullable=False)
    op.alter_column('microsoft_prices', 'segment',
               existing_type=sa.Enum('Commercial', 'Education', 'Charity', name='pricing_segment', schema='optimizer'),
               type_=postgresql.ENUM('Commercial', 'Education', 'Charity', name='pricing_segment'),
               existing_nullable=False)
    op.drop_constraint(None, 'license_assignments', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('license_assignments_user_id_fkey', 'license_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('license_assignments', 'source',
               existing_type=sa.Enum('manual', 'auto', 'group_policy', name='assignment_source', schema='optimizer'),
               type_=postgresql.ENUM('manual', 'auto', 'group_policy', name='assignment_source'),
               existing_nullable=False)
    op.alter_column('license_assignments', 'status',
               existing_type=sa.Enum('active', 'suspended', 'disabled', 'trial', name='license_status', schema='optimizer'),
               type_=postgresql.ENUM('active', 'suspended', 'disabled', 'trial', name='license_status'),
               existing_nullable=False)
    op.drop_constraint(None, 'analytics_snapshots', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('analytics_snapshots_tenant_client_id_fkey', 'analytics_snapshots', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analytics_snapshots', 'snapshot_type',
               existing_type=postgresql.ENUM('license_inventory', 'user_inventory', 'service_usage', 'security_status', 'cost_analysis', 'optimization_recommendations', name='snapshot_type', schema='optimizer'),
               type_=postgresql.ENUM('license_inventory', 'user_inventory', 'service_usage', 'security_status', 'cost_analysis', 'optimization_recommendations', name='snapshot_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'analytics_metrics', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('analytics_metrics_tenant_client_id_fkey', 'analytics_metrics', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analytics_metrics', 'metric_type',
               existing_type=postgresql.ENUM('license_utilization', 'license_cost', 'license_savings', 'license_efficiency', 'active_users', 'inactive_users', 'disabled_users', 'guest_users', 'exchange_usage', 'sharepoint_usage', 'teams_usage', 'onedrive_usage', 'mfa_coverage', 'risk_score', 'compliance_score', name='metric_type', schema='optimizer'),
               type_=postgresql.ENUM('license_utilization', 'license_cost', 'license_savings', 'license_efficiency', 'active_users', 'inactive_users', 'disabled_users', 'guest_users', 'exchange_usage', 'sharepoint_usage', 'teams_usage', 'onedrive_usage', 'mfa_coverage', 'risk_score', 'compliance_score', name='metric_type'),
               existing_nullable=False)
    op.drop_constraint(None, 'analyses', schema='optimizer', type_='foreignkey')
    op.create_foreign_key('analyses_tenant_client_id_fkey', 'analyses', 'tenant_clients', ['tenant_client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('analyses', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='analysis_status', schema='optimizer'),
               type_=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='analysis_status'),
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'expiration_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Date when this mapping expires',
               existing_nullable=True)
    op.alter_column('addon_compatibility', 'effective_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Date when this mapping becomes effective',
               existing_nullable=True)
    op.alter_column('addon_compatibility', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Whether this mapping is active',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'requires_tenant_validation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Requires tenant-level validation',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'requires_domain_validation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Requires domain-level validation',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'quantity_multiplier',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='Quantity must be multiple of this value',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'min_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='Minimum quantity required',
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'addon_category',
               existing_type=sa.VARCHAR(length=100),
               comment='Category of add-on (e.g., "Storage", "Calling Plan")',
               existing_comment="Category of add-on (e.g., 'Storage', 'Calling Plan')",
               existing_nullable=False)
    op.alter_column('addon_compatibility', 'service_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Service type (e.g., "Microsoft 365", "Dynamics 365")',
               existing_comment="Service type (e.g., 'Microsoft 365', 'Dynamics 365')",
               existing_nullable=False)
    op.drop_index(op.f('ix_optimizer_audit_logs_user_id'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_tenant_id'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_response_status'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_request_id'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_level'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_endpoint'), table_name='audit_logs', schema='optimizer')
    op.drop_index(op.f('ix_optimizer_audit_logs_action'), table_name='audit_logs', schema='optimizer')
    op.drop_table('audit_logs', schema='optimizer')
    # ### end Alembic commands ###
