"""LOT2 - Schéma complet validé (10 tables + indexes + enums + vue)

Revision ID: 5b0d2cfdd9c8
Revises: 6eae1f7afccd
Create Date: 2025-11-18 22:44:06.758188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0d2cfdd9c8'
down_revision: Union[str, Sequence[str], None] = '6eae1f7afccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
