"""Initial schema: tenants, users, licenses

Revision ID: 6eae1f7afccd
Revises: 
Create Date: 2025-11-17 20:18:10.135880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eae1f7afccd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_clients',
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='Azure AD Tenant ID'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False, comment='ISO 3166-1 alpha-2 country code'),
    sa.Column('default_language', sa.String(length=5), nullable=False, comment='Default language (fr or en)'),
    sa.Column('onboarding_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='onboardingstatus'), nullable=False),
    sa.Column('csp_customer_id', sa.String(length=36), nullable=True, comment='Partner Center Customer ID'),
    sa.Column('metadatas', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional tenant metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_clients_tenant_id'), 'tenant_clients', ['tenant_id'], unique=True)
    op.create_table('tenant_app_registrations',
    sa.Column('tenant_client_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False, comment='Azure AD Application (client) ID'),
    sa.Column('client_secret', sa.Text(), nullable=True, comment='Encrypted client secret (use Fernet)'),
    sa.Column('certificate_thumbprint', sa.String(length=64), nullable=True, comment='Certificate thumbprint if using certificate auth'),
    sa.Column('authority_url', sa.String(length=255), nullable=False, comment='Azure AD authority URL'),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of Microsoft Graph API scopes'),
    sa.Column('consent_status', sa.Enum('PENDING', 'GRANTED', 'EXPIRED', 'REVOKED', name='consentstatus'), nullable=False),
    sa.Column('consent_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='Whether credentials have been validated'),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_client_id'], ['tenant_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_app_registrations_tenant_client_id'), 'tenant_app_registrations', ['tenant_client_id'], unique=True)
    op.create_table('users',
    sa.Column('graph_id', sa.String(length=36), nullable=False, comment='Microsoft Graph User ID'),
    sa.Column('tenant_client_id', sa.UUID(), nullable=False),
    sa.Column('user_principal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('account_enabled', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('office_location', sa.String(length=255), nullable=True),
    sa.Column('member_of_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Filtered Azure AD groups (DEPT-*, LIC-*, Executives)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_client_id'], ['tenant_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_graph_id'), 'users', ['graph_id'], unique=True)
    op.create_index(op.f('ix_users_tenant_client_id'), 'users', ['tenant_client_id'], unique=False)
    op.create_index(op.f('ix_users_user_principal_name'), 'users', ['user_principal_name'], unique=False)
    op.create_table('license_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.String(length=36), nullable=False, comment='Microsoft SKU ID (GUID)'),
    sa.Column('assignment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='licensestatus'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'GROUP_BASED', 'AUTO', name='assignmentsource'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sku_id', name='uq_user_sku')
    )
    op.create_index(op.f('ix_license_assignments_sku_id'), 'license_assignments', ['sku_id'], unique=False)
    op.create_index(op.f('ix_license_assignments_user_id'), 'license_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_assignments_user_id'), table_name='license_assignments')
    op.drop_index(op.f('ix_license_assignments_sku_id'), table_name='license_assignments')
    op.drop_table('license_assignments')
    op.drop_index(op.f('ix_users_user_principal_name'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_client_id'), table_name='users')
    op.drop_index(op.f('ix_users_graph_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_app_registrations_tenant_client_id'), table_name='tenant_app_registrations')
    op.drop_table('tenant_app_registrations')
    op.drop_index(op.f('ix_tenant_clients_tenant_id'), table_name='tenant_clients')
    op.drop_table('tenant_clients')
    # ### end Alembic commands ###
