"""Add analytics tables for metrics and snapshots

Revision ID: f3a60987c211
Revises: 94b112f77329
Create Date: 2025-11-29 00:41:03.932650

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a60987c211"
down_revision: Union[str, Sequence[str], None] = "94b112f77329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_metrics",
        sa.Column("tenant_client_id", sa.UUID(), nullable=False),
        sa.Column(
            "metric_type",
            postgresql.ENUM(
                "license_utilization",
                "license_cost",
                "license_savings",
                "license_efficiency",
                "active_users",
                "inactive_users",
                "disabled_users",
                "guest_users",
                "exchange_usage",
                "sharepoint_usage",
                "teams_usage",
                "onedrive_usage",
                "mfa_coverage",
                "risk_score",
                "compliance_score",
                name="metric_type",
                schema="optimizer",
            ),
            nullable=False,
        ),
        sa.Column(
            "metric_name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable metric name",
        ),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=False,
            comment="Metric value (can be number, percentage, etc.)",
        ),
        sa.Column(
            "period_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Start of the measurement period",
        ),
        sa.Column(
            "period_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="End of the measurement period",
        ),
        sa.Column(
            "unit",
            sa.String(length=50),
            nullable=True,
            comment="Unit of measurement (%, users, GB, etc.)",
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional context data for the metric",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_client_id"], ["optimizer.tenant_clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="optimizer",
    )
    op.create_index(
        "idx_analytics_metrics_period",
        "analytics_metrics",
        ["period_start", "period_end"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        "idx_analytics_metrics_tenant_type",
        "analytics_metrics",
        ["tenant_client_id", "metric_type"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        "idx_analytics_metrics_type_period",
        "analytics_metrics",
        ["metric_type", "period_start"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_metrics_metric_type"),
        "analytics_metrics",
        ["metric_type"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_metrics_period_start"),
        "analytics_metrics",
        ["period_start"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_metrics_tenant_client_id"),
        "analytics_metrics",
        ["tenant_client_id"],
        unique=False,
        schema="optimizer",
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column("tenant_client_id", sa.UUID(), nullable=False),
        sa.Column(
            "snapshot_type",
            postgresql.ENUM(
                "license_inventory",
                "user_inventory",
                "service_usage",
                "security_status",
                "cost_analysis",
                "optimization_recommendations",
                name="snapshot_type",
                schema="optimizer",
            ),
            nullable=False,
        ),
        sa.Column(
            "snapshot_date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Date when the snapshot was taken",
        ),
        sa.Column(
            "snapshot_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Snapshot data in JSON format",
        ),
        sa.Column(
            "snapshot_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional metadata about the snapshot",
        ),
        sa.Column(
            "data_hash",
            sa.String(length=64),
            nullable=True,
            comment="SHA-256 hash of the snapshot data for integrity checking",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_client_id"], ["optimizer.tenant_clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="optimizer",
    )
    op.create_index(
        "idx_analytics_snapshots_tenant_type_date",
        "analytics_snapshots",
        ["tenant_client_id", "snapshot_type", "snapshot_date"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        "idx_analytics_snapshots_type_date",
        "analytics_snapshots",
        ["snapshot_type", "snapshot_date"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_snapshots_snapshot_date"),
        "analytics_snapshots",
        ["snapshot_date"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_snapshots_snapshot_type"),
        "analytics_snapshots",
        ["snapshot_type"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analytics_snapshots_tenant_client_id"),
        "analytics_snapshots",
        ["tenant_client_id"],
        unique=False,
        schema="optimizer",
    )
    op.alter_column(
        "analyses",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "COMPLETED", "FAILED", name="analysis_status"
        ),
        server_default=None,
        type_=sa.Enum(
            "PENDING", "COMPLETED", "FAILED", name="analysis_status", schema="optimizer"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "summary",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_comment="Analysis summary with totals, costs, savings, and breakdown",
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_analyses_analysis_date", table_name="analyses")
    op.drop_index("ix_analyses_status", table_name="analyses")
    op.drop_index("ix_analyses_tenant_client_id", table_name="analyses")
    op.create_index(
        op.f("ix_optimizer_analyses_analysis_date"),
        "analyses",
        ["analysis_date"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analyses_status"),
        "analyses",
        ["status"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_analyses_tenant_client_id"),
        "analyses",
        ["tenant_client_id"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint("analyses_tenant_client_id_fkey", "analyses", type_="foreignkey")
    op.create_foreign_key(
        None,
        "analyses",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "license_assignments",
        "sku_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Microsoft SKU ID (GUID)",
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "status",
        existing_type=postgresql.ENUM(
            "active", "suspended", "disabled", "trial", name="license_status"
        ),
        server_default=None,
        type_=postgresql.ENUM(
            "ACTIVE", "SUSPENDED", "DISABLED", "TRIAL", name="license_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "source",
        existing_type=postgresql.ENUM(
            "manual", "auto", "group_policy", name="assignment_source"
        ),
        server_default=None,
        type_=postgresql.ENUM(
            "manual", "auto", "group_policy", name="assignment_source"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_license_assignments_sku_id", table_name="license_assignments")
    op.drop_index("ix_license_assignments_user_id", table_name="license_assignments")
    op.create_index(
        op.f("ix_optimizer_license_assignments_sku_id"),
        "license_assignments",
        ["sku_id"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_license_assignments_user_id"),
        "license_assignments",
        ["user_id"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint(
        "license_assignments_user_id_fkey", "license_assignments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "license_assignments",
        "users",
        ["user_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "microsoft_prices",
        "segment",
        existing_type=postgresql.ENUM(
            "Commercial", "Education", "Charity", name="pricing_segment"
        ),
        type_=sa.Enum(
            "Commercial",
            "Education",
            "Charity",
            name="pricing_segment",
            schema="optimizer",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "microsoft_prices",
        "billing_plan",
        existing_type=postgresql.ENUM("Annual", "Monthly", name="billing_plan"),
        type_=sa.Enum("Annual", "Monthly", name="billing_plan", schema="optimizer"),
        existing_nullable=False,
    )
    op.alter_column(
        "microsoft_prices",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(
        "microsoft_prices_product_id_sku_id_fkey",
        "microsoft_prices",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "microsoft_prices",
        "microsoft_products",
        ["product_id", "sku_id"],
        ["product_id", "sku_id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "microsoft_products",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "savings_monthly",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default=None,
        existing_comment="Monthly savings (can be negative for upgrades)",
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "reason",
        existing_type=sa.TEXT(),
        comment="Explanation for recommendation (e.g., 'Inactive user >90 days')",
        existing_comment="Explanation for recommendation",
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "ACCEPTED", "REJECTED", name="recommendation_status"
        ),
        server_default=None,
        type_=sa.Enum(
            "PENDING",
            "ACCEPTED",
            "REJECTED",
            name="recommendation_status",
            schema="optimizer",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_recommendations_analysis_id", table_name="recommendations")
    op.drop_index("ix_recommendations_status", table_name="recommendations")
    op.drop_index("ix_recommendations_user_id", table_name="recommendations")
    op.create_index(
        op.f("ix_optimizer_recommendations_analysis_id"),
        "recommendations",
        ["analysis_id"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_recommendations_status"),
        "recommendations",
        ["status"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_recommendations_user_id"),
        "recommendations",
        ["user_id"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint(
        "recommendations_analysis_id_fkey", "recommendations", type_="foreignkey"
    )
    op.drop_constraint(
        "recommendations_user_id_fkey", "recommendations", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "recommendations",
        "users",
        ["user_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "recommendations",
        "analyses",
        ["analysis_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "reports",
        "report_type",
        existing_type=sa.VARCHAR(length=10),
        comment="PDF or EXCEL",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "file_name",
        existing_type=sa.VARCHAR(length=255),
        comment="Original filename",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "file_path",
        existing_type=sa.VARCHAR(length=500),
        comment="Storage path",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "report_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="KPIs, stats, chart data",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "generated_by",
        existing_type=sa.VARCHAR(length=255),
        comment="User email who generated",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="TTL for cleanup",
        existing_nullable=True,
    )
    op.drop_index("ix_reports_analysis_id", table_name="reports")
    op.drop_index("ix_reports_created_at", table_name="reports")
    op.drop_index("ix_reports_expires_at", table_name="reports")
    op.drop_index("ix_reports_report_type", table_name="reports")
    op.drop_index("ix_reports_tenant_client_id", table_name="reports")
    op.create_index(
        op.f("ix_optimizer_reports_analysis_id"),
        "reports",
        ["analysis_id"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_reports_tenant_client_id"),
        "reports",
        ["tenant_client_id"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint("reports_tenant_client_id_fkey", "reports", type_="foreignkey")
    op.drop_constraint("reports_analysis_id_fkey", "reports", type_="foreignkey")
    op.create_foreign_key(
        None,
        "reports",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "reports",
        "analyses",
        ["analysis_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.drop_column("reports", "updated_at")
    op.alter_column(
        "tenant_app_registrations",
        "client_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Azure AD Application (client) ID",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "client_secret_encrypted",
        existing_type=sa.TEXT(),
        comment="Encrypted client secret (use Fernet)",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_app_registrations",
        "certificate_thumbprint",
        existing_type=sa.VARCHAR(length=64),
        comment="Certificate thumbprint if using certificate auth",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_app_registrations",
        "authority_url",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        comment="Azure AD authority URL",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "scopes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="List of Microsoft Graph API scopes",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "consent_status",
        existing_type=postgresql.ENUM(
            "pending", "granted", "revoked", "expired", name="consent_status"
        ),
        server_default=None,
        type_=postgresql.ENUM(
            "pending",
            "granted",
            "expired",
            "revoked",
            name="consent_status",
            schema="optimizer",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "is_valid",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        comment="Whether credentials have been validated",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        "ix_tenant_app_registrations_tenant_client_id",
        table_name="tenant_app_registrations",
    )
    op.create_index(
        op.f("ix_optimizer_tenant_app_registrations_tenant_client_id"),
        "tenant_app_registrations",
        ["tenant_client_id"],
        unique=True,
        schema="optimizer",
    )
    op.drop_constraint(
        "tenant_app_registrations_tenant_client_id_fkey",
        "tenant_app_registrations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "tenant_app_registrations",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "tenant_clients",
        "country",
        existing_type=sa.VARCHAR(length=2),
        comment="ISO 3166-1 alpha-2 country code",
        existing_comment="ISO 3166-1 alpha-2",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "default_language",
        existing_type=sa.VARCHAR(length=5),
        server_default=None,
        comment="Default language (fr or en)",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "onboarding_status",
        existing_type=postgresql.ENUM(
            "pending", "active", "suspended", "error", name="onboarding_status"
        ),
        server_default=None,
        type_=postgresql.ENUM(
            "pending",
            "active",
            "suspended",
            "error",
            name="onboarding_status",
            schema="optimizer",
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "csp_customer_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Partner Center Customer ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_clients",
        "metadatas",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="Additional tenant metadata",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_clients",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_tenant_clients_tenant_id", table_name="tenant_clients")
    op.create_index(
        op.f("ix_optimizer_tenant_clients_tenant_id"),
        "tenant_clients",
        ["tenant_id"],
        unique=True,
        schema="optimizer",
    )
    op.alter_column(
        "usage_metrics",
        "period",
        existing_type=sa.VARCHAR(length=10),
        comment="Period: D7, D28, D90, D180",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "report_date",
        existing_type=sa.DATE(),
        comment="Date of the report",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "last_seen_date",
        existing_type=sa.DATE(),
        comment="Last activity date",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "email_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="Email activity metrics (send_count, receive_count, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "onedrive_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="OneDrive activity metrics (viewed, edited, synced, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "sharepoint_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="SharePoint activity metrics (viewed, edited, shared, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "teams_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="Teams activity metrics (messages, calls, meetings, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "office_web_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="Office web activity (Word, Excel, PowerPoint online)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "office_desktop_activated",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        comment="Office desktop activated",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "storage_used_bytes",
        existing_type=sa.BIGINT(),
        server_default=None,
        comment="OneDrive storage used (bytes)",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "mailbox_size_bytes",
        existing_type=sa.BIGINT(),
        server_default=None,
        comment="Mailbox size (bytes)",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_usage_metrics_report_date", table_name="usage_metrics")
    op.drop_index("ix_usage_metrics_user_id", table_name="usage_metrics")
    op.create_index(
        op.f("ix_optimizer_usage_metrics_report_date"),
        "usage_metrics",
        ["report_date"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_usage_metrics_user_id"),
        "usage_metrics",
        ["user_id"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint(
        "usage_metrics_user_id_fkey", "usage_metrics", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "usage_metrics",
        "users",
        ["user_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    op.alter_column(
        "users",
        "graph_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Microsoft Graph User ID",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "account_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        comment="Hashed password for authentication (partner users only)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "member_of_groups",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        comment="Filtered Azure AD groups (DEPT-*, LIC-*, Executives)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index("ix_users_graph_id", table_name="users")
    op.drop_index("ix_users_tenant_client_id", table_name="users")
    op.drop_index("ix_users_user_principal_name", table_name="users")
    op.create_index(
        op.f("ix_optimizer_users_graph_id"),
        "users",
        ["graph_id"],
        unique=True,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_users_tenant_client_id"),
        "users",
        ["tenant_client_id"],
        unique=False,
        schema="optimizer",
    )
    op.create_index(
        op.f("ix_optimizer_users_user_principal_name"),
        "users",
        ["user_principal_name"],
        unique=False,
        schema="optimizer",
    )
    op.drop_constraint("users_tenant_client_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        None,
        "users",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        source_schema="optimizer",
        referent_schema="optimizer",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "users_tenant_client_id_fkey",
        "users",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_users_user_principal_name"),
        table_name="users",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_users_tenant_client_id"),
        table_name="users",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_users_graph_id"), table_name="users", schema="optimizer"
    )
    op.create_index(
        "ix_users_user_principal_name", "users", ["user_principal_name"], unique=False
    )
    op.create_index(
        "ix_users_tenant_client_id", "users", ["tenant_client_id"], unique=False
    )
    op.create_index("ix_users_graph_id", "users", ["graph_id"], unique=False)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "member_of_groups",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        comment=None,
        existing_comment="Filtered Azure AD groups (DEPT-*, LIC-*, Executives)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Hashed password for authentication (partner users only)",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "account_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "graph_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Microsoft Graph User ID",
        existing_nullable=False,
    )
    op.drop_constraint(None, "usage_metrics", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "usage_metrics_user_id_fkey",
        "usage_metrics",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_usage_metrics_user_id"),
        table_name="usage_metrics",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_usage_metrics_report_date"),
        table_name="usage_metrics",
        schema="optimizer",
    )
    op.create_index(
        "ix_usage_metrics_user_id", "usage_metrics", ["user_id"], unique=False
    )
    op.create_index(
        "ix_usage_metrics_report_date", "usage_metrics", ["report_date"], unique=False
    )
    op.alter_column(
        "usage_metrics",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "mailbox_size_bytes",
        existing_type=sa.BIGINT(),
        server_default=sa.text("'0'::bigint"),
        comment=None,
        existing_comment="Mailbox size (bytes)",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "storage_used_bytes",
        existing_type=sa.BIGINT(),
        server_default=sa.text("'0'::bigint"),
        comment=None,
        existing_comment="OneDrive storage used (bytes)",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "office_desktop_activated",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        comment=None,
        existing_comment="Office desktop activated",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "office_web_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="Office web activity (Word, Excel, PowerPoint online)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "teams_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="Teams activity metrics (messages, calls, meetings, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "sharepoint_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="SharePoint activity metrics (viewed, edited, shared, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "onedrive_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="OneDrive activity metrics (viewed, edited, synced, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "email_activity",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="Email activity metrics (send_count, receive_count, etc.)",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "last_seen_date",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="Last activity date",
        existing_nullable=True,
    )
    op.alter_column(
        "usage_metrics",
        "report_date",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="Date of the report",
        existing_nullable=False,
    )
    op.alter_column(
        "usage_metrics",
        "period",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Period: D7, D28, D90, D180",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_optimizer_tenant_clients_tenant_id"),
        table_name="tenant_clients",
        schema="optimizer",
    )
    op.create_index(
        "ix_tenant_clients_tenant_id", "tenant_clients", ["tenant_id"], unique=False
    )
    op.alter_column(
        "tenant_clients",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "metadatas",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        comment=None,
        existing_comment="Additional tenant metadata",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_clients",
        "csp_customer_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Partner Center Customer ID",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_clients",
        "onboarding_status",
        existing_type=postgresql.ENUM(
            "pending",
            "active",
            "suspended",
            "error",
            name="onboarding_status",
            schema="optimizer",
        ),
        server_default=sa.text("'pending'::onboarding_status"),
        type_=postgresql.ENUM(
            "pending", "active", "suspended", "error", name="onboarding_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "default_language",
        existing_type=sa.VARCHAR(length=5),
        server_default=sa.text("'fr-FR'::character varying"),
        comment=None,
        existing_comment="Default language (fr or en)",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_clients",
        "country",
        existing_type=sa.VARCHAR(length=2),
        comment="ISO 3166-1 alpha-2",
        existing_comment="ISO 3166-1 alpha-2 country code",
        existing_nullable=False,
    )
    op.drop_constraint(
        None, "tenant_app_registrations", schema="optimizer", type_="foreignkey"
    )
    op.create_foreign_key(
        "tenant_app_registrations_tenant_client_id_fkey",
        "tenant_app_registrations",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_tenant_app_registrations_tenant_client_id"),
        table_name="tenant_app_registrations",
        schema="optimizer",
    )
    op.create_index(
        "ix_tenant_app_registrations_tenant_client_id",
        "tenant_app_registrations",
        ["tenant_client_id"],
        unique=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "is_valid",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        comment=None,
        existing_comment="Whether credentials have been validated",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "consent_status",
        existing_type=postgresql.ENUM(
            "pending",
            "granted",
            "expired",
            "revoked",
            name="consent_status",
            schema="optimizer",
        ),
        server_default=sa.text("'pending'::consent_status"),
        type_=postgresql.ENUM(
            "pending", "granted", "revoked", "expired", name="consent_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "scopes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[]'::jsonb"),
        comment=None,
        existing_comment="List of Microsoft Graph API scopes",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "authority_url",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text(
            "'https://login.microsoftonline.com/common'::character varying"
        ),
        comment=None,
        existing_comment="Azure AD authority URL",
        existing_nullable=False,
    )
    op.alter_column(
        "tenant_app_registrations",
        "certificate_thumbprint",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Certificate thumbprint if using certificate auth",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_app_registrations",
        "client_secret_encrypted",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Encrypted client secret (use Fernet)",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_app_registrations",
        "client_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Azure AD Application (client) ID",
        existing_nullable=False,
    )
    op.add_column(
        "reports",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "reports", schema="optimizer", type_="foreignkey")
    op.drop_constraint(None, "reports", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "reports_analysis_id_fkey",
        "reports",
        "analyses",
        ["analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "reports_tenant_client_id_fkey",
        "reports",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_reports_tenant_client_id"),
        table_name="reports",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_reports_analysis_id"),
        table_name="reports",
        schema="optimizer",
    )
    op.create_index(
        "ix_reports_tenant_client_id", "reports", ["tenant_client_id"], unique=False
    )
    op.create_index("ix_reports_report_type", "reports", ["report_type"], unique=False)
    op.create_index("ix_reports_expires_at", "reports", ["expires_at"], unique=False)
    op.create_index("ix_reports_created_at", "reports", ["created_at"], unique=False)
    op.create_index("ix_reports_analysis_id", "reports", ["analysis_id"], unique=False)
    op.alter_column(
        "reports",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="TTL for cleanup",
        existing_nullable=True,
    )
    op.alter_column(
        "reports",
        "generated_by",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="User email who generated",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "report_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="KPIs, stats, chart data",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "file_path",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Storage path",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "file_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Original filename",
        existing_nullable=False,
    )
    op.alter_column(
        "reports",
        "report_type",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="PDF or EXCEL",
        existing_nullable=False,
    )
    op.drop_constraint(None, "recommendations", schema="optimizer", type_="foreignkey")
    op.drop_constraint(None, "recommendations", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "recommendations_user_id_fkey",
        "recommendations",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "recommendations_analysis_id_fkey",
        "recommendations",
        "analyses",
        ["analysis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_recommendations_user_id"),
        table_name="recommendations",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_recommendations_status"),
        table_name="recommendations",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_recommendations_analysis_id"),
        table_name="recommendations",
        schema="optimizer",
    )
    op.create_index(
        "ix_recommendations_user_id", "recommendations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_recommendations_status", "recommendations", ["status"], unique=False
    )
    op.create_index(
        "ix_recommendations_analysis_id",
        "recommendations",
        ["analysis_id"],
        unique=False,
    )
    op.alter_column(
        "recommendations",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "status",
        existing_type=sa.Enum(
            "PENDING",
            "ACCEPTED",
            "REJECTED",
            name="recommendation_status",
            schema="optimizer",
        ),
        server_default=sa.text("'PENDING'::recommendation_status"),
        type_=postgresql.ENUM(
            "PENDING", "ACCEPTED", "REJECTED", name="recommendation_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "reason",
        existing_type=sa.TEXT(),
        comment="Explanation for recommendation",
        existing_comment="Explanation for recommendation (e.g., 'Inactive user >90 days')",
        existing_nullable=False,
    )
    op.alter_column(
        "recommendations",
        "savings_monthly",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default=sa.text("0.00"),
        existing_comment="Monthly savings (can be negative for upgrades)",
        existing_nullable=False,
    )
    op.alter_column(
        "microsoft_products",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "microsoft_prices", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "microsoft_prices_product_id_sku_id_fkey",
        "microsoft_prices",
        "microsoft_products",
        ["product_id", "sku_id"],
        ["product_id", "sku_id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "microsoft_prices",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "microsoft_prices",
        "billing_plan",
        existing_type=sa.Enum(
            "Annual", "Monthly", name="billing_plan", schema="optimizer"
        ),
        type_=postgresql.ENUM("Annual", "Monthly", name="billing_plan"),
        existing_nullable=False,
    )
    op.alter_column(
        "microsoft_prices",
        "segment",
        existing_type=sa.Enum(
            "Commercial",
            "Education",
            "Charity",
            name="pricing_segment",
            schema="optimizer",
        ),
        type_=postgresql.ENUM(
            "Commercial", "Education", "Charity", name="pricing_segment"
        ),
        existing_nullable=False,
    )
    op.drop_constraint(
        None, "license_assignments", schema="optimizer", type_="foreignkey"
    )
    op.create_foreign_key(
        "license_assignments_user_id_fkey",
        "license_assignments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_license_assignments_user_id"),
        table_name="license_assignments",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_license_assignments_sku_id"),
        table_name="license_assignments",
        schema="optimizer",
    )
    op.create_index(
        "ix_license_assignments_user_id",
        "license_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_license_assignments_sku_id", "license_assignments", ["sku_id"], unique=False
    )
    op.alter_column(
        "license_assignments",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "source",
        existing_type=postgresql.ENUM(
            "MANUAL", "AUTO", "GROUP_POLICY", name="assignment_source"
        ),
        server_default=sa.text("'manual'::assignment_source"),
        type_=postgresql.ENUM(
            "manual", "auto", "group_policy", name="assignment_source"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "status",
        existing_type=postgresql.ENUM(
            "ACTIVE", "SUSPENDED", "DISABLED", "TRIAL", name="license_status"
        ),
        server_default=sa.text("'active'::license_status"),
        type_=postgresql.ENUM(
            "active", "suspended", "disabled", "trial", name="license_status"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "license_assignments",
        "sku_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Microsoft SKU ID (GUID)",
        existing_nullable=False,
    )
    op.drop_constraint(None, "analyses", schema="optimizer", type_="foreignkey")
    op.create_foreign_key(
        "analyses_tenant_client_id_fkey",
        "analyses",
        "tenant_clients",
        ["tenant_client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_optimizer_analyses_tenant_client_id"),
        table_name="analyses",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_analyses_status"), table_name="analyses", schema="optimizer"
    )
    op.drop_index(
        op.f("ix_optimizer_analyses_analysis_date"),
        table_name="analyses",
        schema="optimizer",
    )
    op.create_index(
        "ix_analyses_tenant_client_id", "analyses", ["tenant_client_id"], unique=False
    )
    op.create_index("ix_analyses_status", "analyses", ["status"], unique=False)
    op.create_index(
        "ix_analyses_analysis_date", "analyses", ["analysis_date"], unique=False
    )
    op.alter_column(
        "analyses",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "summary",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_comment="Analysis summary with totals, costs, savings, and breakdown",
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "status",
        existing_type=sa.Enum(
            "PENDING", "COMPLETED", "FAILED", name="analysis_status", schema="optimizer"
        ),
        server_default=sa.text("'PENDING'::analysis_status"),
        type_=postgresql.ENUM("PENDING", "COMPLETED", "FAILED", name="analysis_status"),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_optimizer_analytics_snapshots_tenant_client_id"),
        table_name="analytics_snapshots",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_analytics_snapshots_snapshot_type"),
        table_name="analytics_snapshots",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_analytics_snapshots_snapshot_date"),
        table_name="analytics_snapshots",
        schema="optimizer",
    )
    op.drop_index(
        "idx_analytics_snapshots_type_date",
        table_name="analytics_snapshots",
        schema="optimizer",
    )
    op.drop_index(
        "idx_analytics_snapshots_tenant_type_date",
        table_name="analytics_snapshots",
        schema="optimizer",
    )
    op.drop_table("analytics_snapshots", schema="optimizer")
    op.drop_index(
        op.f("ix_optimizer_analytics_metrics_tenant_client_id"),
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_analytics_metrics_period_start"),
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_index(
        op.f("ix_optimizer_analytics_metrics_metric_type"),
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_index(
        "idx_analytics_metrics_type_period",
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_index(
        "idx_analytics_metrics_tenant_type",
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_index(
        "idx_analytics_metrics_period",
        table_name="analytics_metrics",
        schema="optimizer",
    )
    op.drop_table("analytics_metrics", schema="optimizer")
    # ### end Alembic commands ###
