#!/bin/bash

echo "🔧 CORRECTION COMPLETE: Traduire TOUS les champs des rapports"
echo "============================================================="

cd "/mnt/d/DOC G/Projets/m365-license-optimizer"

# ÉTAPE 1: Ajouter les traductions manquantes dans i18n_service
echo "1️⃣ Ajout des traductions manquantes..."

cat > /tmp/add_all_translations.py << 'PYEOF'
import re

# Lire i18n_service.py
file_path = "backend/src/services/i18n_service.py"
with open(file_path, 'r') as f:
    content = f.read()

# Définir les traductions manquantes
translations_to_add = {
    "en": {
        # Excel - Summary sheet
        "report.title.excel_summary": "Microsoft 365 License Optimization Summary",
        "report.generated_at": "Report generated",
        "report.kpi_section": "Key Performance Indicators",
        "report.current_monthly_cost": "Current Monthly Cost",
        "report.target_monthly_cost": "Target Monthly Cost",
        "report.monthly_savings": "Monthly Savings",
        "report.annual_savings": "Annual Savings",
        "report.savings_percentage": "Savings Percentage",
        "report.license_distribution": "License Distribution",
        "report.total_users": "Total Users",
        "report.period": "Period",
        
        # Excel - Detailed sheet
        "report.detailed_recommendations": "Detailed Recommendations by User",
        "report.user_principal_name": "User Principal Name",
        "report.display_name": "Display Name",
        "report.department": "Department",
        "report.job_title": "Job Title",
        "report.current_license": "Current License",
        "report.current_monthly_cost": "Current Monthly Cost",
        "report.recommended_license": "Recommended License",
        "report.recommended_monthly_cost": "Recommended Monthly Cost",
        "report.monthly_savings": "Monthly Savings",
        "report.annual_savings": "Annual Savings",
        "report.exchange_usage_level": "Exchange Usage Level",
        "report.onedrive_usage_gb": "OneDrive Usage (GB)",
        "report.teams_activity": "Teams Activity",
        "report.office_desktop_required": "Office Desktop Required",
        "report.last_activity_date": "Last Activity Date",
        "report.inactivity_days": "Inactivity Days",
        "report.recommendation_status": "Recommendation Status",
        "report.recommendation_reason": "Recommendation Reason",
        "report.yes": "Yes",
        "report.no": "No",
        "report.proposed": "Proposed",
        "report.validated": "Validated",
        "report.rejected": "Rejected",
        "report.sensitive": "Sensitive",
        
        # Excel - Raw data sheet
        "report.raw_data": "Raw Data Analysis",
        "report.total_users_kpi": "Total Users",
        "report.monthly_savings_kpi": "Monthly Savings",
        "report.annual_savings_kpi": "Annual Savings",
        
        # PDF - Headers
        "report.title.pdf_summary": "Microsoft 365 License Optimization Report",
        "report.generated_by": "Generated by",
        "report.tenant": "Tenant",
        "report.to": "to",
        
        # PDF - KPIs
        "report.total_monthly_cost": "Total Monthly Cost",
        "report.optimized_monthly_cost": "Optimized Monthly Cost",
        "report.potential_monthly_savings": "Potential Monthly Savings",
        "report.potential_annual_savings": "Potential Annual Savings",
        "report.savings_rate": "Savings Rate",
        "report.total_licenses_deployed": "Total Licenses Deployed",
        "report.license_distribution": "License Distribution",
        "report.top_recommendations": "Top Recommendations by Savings",
        "report.by_departments": "Optimization Summary by Departments",
        
        # PDF - Table headers
        "report.current_sku": "Current SKU",
        "report.target_sku": "Target SKU",
        "report.monthly_savings_per_user": "Monthly Savings/User",
        "report.annual_savings_per_user": "Annual Savings/User",
        "report.user_count": "User Count",
        "report.department": "Department",
        "report.current_cost": "Current Cost",
        "report.optimized_cost": "Optimized Cost",
        "report.annual_savings_dept": "Annual Savings",
    },
    "fr": {
        # Excel - Summary sheet
        "report.title.excel_summary": "SYNTHÈSE - ANALYSE D'OPTIMISATION MICROSOFT 365",
        "report.generated_at": "Date de génération",
        "report.kpi_section": "INDICATEURS CLÉS",
        "report.current_monthly_cost": "Coût actuel mensuel",
        "report.target_monthly_cost": "Coût cible mensuel",
        "report.monthly_savings": "Économie mensuelle",
        "report.annual_savings": "Économie annuelle",
        "report.savings_percentage": "Taux d'économie",
        "report.license_distribution": "Répartition des licences",
        "report.total_users": "Nombre total d'utilisateurs",
        "report.period": "Période",
        
        # Excel - Detailed sheet
        "report.detailed_recommendations": "Recommandations détaillées par utilisateur",
        "report.user_principal_name": "Nom d'utilisateur principal",
        "report.display_name": "Nom d'affichage",
        "report.department": "Département",
        "report.job_title": "Titre du poste",
        "report.current_license": "Licence actuelle",
        "report.current_monthly_cost": "Coût mensuel actuel",
        "report.recommended_license": "Licence recommandée",
        "report.recommended_monthly_cost": "Coût mensuel recommandé",
        "report.monthly_savings": "Économies mensuelles",
        "report.annual_savings": "Économies annuelles",
        "report.exchange_usage_level": "Niveau d'utilisation Exchange",
        "report.onedrive_usage_gb": "Utilisation OneDrive (Go)",
        "report.teams_activity": "Activité Teams",
        "report.office_desktop_required": "Bureau Office requis",
        "report.last_activity_date": "Date dernière activité",
        "report.inactivity_days": "Jours d'inactivité",
        "report.recommendation_status": "Statut recommandation",
        "report.recommendation_reason": "Raison recommandation",
        "report.yes": "Oui",
        "report.no": "Non",
        "report.proposed": "Proposé",
        "report.validated": "Validé",
        "report.rejected": "Rejeté",
        "report.sensitive": "Sensible",
        
        # Excel - Raw data sheet
        "report.raw_data": "Données brutes d'analyse",
        "report.total_users_kpi": "Nombre total d'utilisateurs",
        "report.monthly_savings_kpi": "Économies mensuelles",
        "report.annual_savings_kpi": "Économies annuelles",
        
        # PDF - Headers
        "report.title.pdf_summary": "RAPPORT D'OPTIMISATION MICROSOFT 365",
        "report.generated_by": "Généré par",
        "report.tenant": "Tenant",
        "report.to": "au",
        
        # PDF - KPIs
        "report.total_monthly_cost": "Coût mensuel total",
        "report.optimized_monthly_cost": "Coût mensuel optimisé",
        "report.potential_monthly_savings": "Économies mensuelles potentielles",
        "report.potential_annual_savings": "Économies annuelles potentielles",
        "report.savings_rate": "Taux d'économies",
        "report.total_licenses_deployed": "Total licences déployées",
        "report.license_distribution": "Distribution des licences",
        "report.top_recommendations": "Top recommandations par économies",
        "report.by_departments": "Résumé par départements",
        
        # PDF - Table headers
        "report.current_sku": "SKU actuel",
        "report.target_sku": "SKU cible",
        "report.monthly_savings_per_user": "Économies mensuelles/Utilisateur",
        "report.annual_savings_per_user": "Économies annuelles/Utilisateur",
        "report.user_count": "Nombre utilisateurs",
        "report.department": "Département",
        "report.current_cost": "Coût actuel",
        "report.optimized_cost": "Coût optimisé",
        "report.annual_savings_dept": "Économies annuelles",
    },
}

# Insérer les traductions manquantes dans la section 'en'
en_section = content.find('"en": {') + 7
fr_section = content.find('"fr": {') + 7

# Pour chaque clé, vérifier si elle existe, sinon l'ajouter
en_insert = []
fr_insert = []

for key in translations_to_add["en"]:
    if f'"{key}":' not in content:
        en_insert.append(f'        "{key}": "{translations_to_add["en"][key]}",')
        fr_insert.append(f'        "{key}": "{translations_to_add["fr"][key]}",')

if en_insert:
    # Insérer après "en": {
    insert_pos = en_section
    content = content[:insert_pos] + "\n" + "\n".join(en_insert) + content[insert_pos:]
    
    # Recalculer fr_section après insertion
    fr_section = content.find('"fr": {') + 7
    content = content[:fr_section] + "\n" + "\n".join(fr_insert) + content[fr_section:]
    
    print(f"✅ {len(en_insert)} traductions EN ajoutées")
    print(f"✅ {len(fr_insert)} traductions FR ajoutées")
else:
    print("✅ Toutes les traductions déjà présentes")

# Sauvegarder
with open(file_path, 'w') as f:
    f.write(content)

print("✅ Traductions ajoutées dans i18n_service.py")
PYEOF

python3 /tmp/add_all_translations.py

# ÉTAPE 2: Corriger les textes en dur dans ExcelGenerator
echo ""
echo "2️⃣ Remplacement des textes en dur dans ExcelGenerator..."

python3 << 'PYEOF'
file_path = "backend/src/services/reports/excel_generator_simple.py"

with open(file_path, 'r') as f:
    content = f.read()

# Dictionnaire des remplacements : texte_français → clé_traduction
replacements = [
    # Summary sheet
    ('"SYNTHÈSE - ANALYSE D\'OPTIMISATION MICROSOFT 365"', 
     'i18n_service.translate("report.title.excel_summary", language)'),
    
    ('f"{i18n_service.translate(\"report.generated_at\", language)}: {i18n_service.format_date(datetime.now(), language, \"long\")}"',
     'f"{i18n_service.translate(\"report.generated_at\", language)}: {i18n_service.format_date(datetime.now(), language, \"long\")}"'),
    
    ('"INDICATEURS CLÉS"',
     'i18n_service.translate("report.kpi_section", language)'),
    
    ('i18n_service.translate("report.current_monthly_cost", language) or "Current Monthly Cost"',
     'i18n_service.translate("report.current_monthly_cost", language)'),
    
    ('i18n_service.translate("report.target_monthly_cost", language) or "Target Monthly Cost"',
     'i18n_service.translate("report.target_monthly_cost", language)'),
    
    ('i18n_service.translate("report.monthly_savings", language) or "Monthly Savings"',
     'i18n_service.translate("report.monthly_savings", language)'),
    
    ('i18n_service.translate("report.annual_savings", language) or "Annual Savings"',
     'i18n_service.translate("report.annual_savings", language)'),
    
    ('i18n_service.translate("report.savings_percentage", language) or "Savings Percentage"',
     'i18n_service.translate("report.savings_percentage", language)'),
    
    ('"RÉPARTITION DES LICENCES"',
     'i18n_service.translate("report.license_distribution", language)'),
    
    # Detailed sheet
    ('"RECOMMANDATIONS DÉTAILLÉES PAR UTILISATEUR"',
     'i18n_service.translate("report.detailed_recommendations", language)'),
    
    ('"Oui"',
     'i18n_service.translate("report.yes", language)'),
    
    ('"Non"',
     'i18n_service.translate("report.no", language)'),
    
    # Raw data sheet
    ('"DONNÉES BRUTES D\'ANALYSE"',
     'i18n_service.translate("report.raw_data", language)'),
    
    ('"Total utilisateurs"',
     'i18n_service.translate("report.total_users_kpi", language)'),
    
    ('"Économies mensuelles"',
     'i18n_service.translate("report.monthly_savings_kpi", language)'),
    
    ('"Économies annuelles"',
     'i18n_service.translate("report.annual_savings_kpi", language)'),
]

# Remplacer chaque occurrence
count = 0
for old, new in replacements:
    if old in content and 'i18n_service.translate' not in old:  # Ne pas remplacer si déjà traduit
        content = content.replace(old, new)
        count += 1

# Écrire le fichier
with open(file_path, 'w') as f:
    f.write(content)

print(f"✅ {count} textes remplacés dans excel_generator_simple.py")
PYEOF

# ÉTAPE 3: Corriger les textes en dur dans PDFGenerator
echo ""
echo "3️⃣ Remplacement des textes en dur dans PDFGenerator..."

python3 << 'PYEOF'
file_path = "backend/src/services/reports/pdf_generator.py"

with open(file_path, 'r') as f:
    content = f.read()

# Dictionnaire des remplacements
replacements = [
    # Headers
    ('i18n_service.translate("report.generated_by", language)',
     'i18n_service.translate("report.generated_by", language)'),
    
    ('i18n_service.translate("report.tenant", language)',
     'i18n_service.translate("report.tenant", language)'),
    
    # Titre principal
    ('i18n_service.translate("report.title.pdf_summary", language)',
     'i18n_service.translate("report.title.pdf_summary", language)'),
    
    # KPIs
    ('"TOTAL MONTHLY COST"',
     'i18n_service.translate("report.total_monthly_cost", language).upper()'),
    
    ('"OPTIMIZED MONTHLY COST"',
     'i18n_service.translate("report.optimized_monthly_cost", language).upper()'),
    
    ('"POTENTIAL MONTHLY SAVINGS"',
     'i18n_service.translate("report.potential_monthly_savings", language).upper()'),
    
    ('"POTENTIAL ANNUAL SAVINGS"',
     'i18n_service.translate("report.potential_annual_savings", language).upper()'),
    
    ('"SAVINGS RATE"',
     'i18n_service.translate("report.savings_rate", language).upper()'),
    
    ('"TOTAL LICENSES DEPLOYED"',
     'i18n_service.translate("report.total_licenses_deployed", language).upper()'),
    
    ('"LICENSE DISTRIBUTION"',
     'i18n_service.translate("report.license_distribution", language).upper()'),
    
    ('"TOP RECOMMENDATIONS BY SAVINGS"',
     'i18n_service.translate("report.top_recommendations", language).upper()'),
    
    ('"OPTIMIZATION SUMMARY BY DEPARTMENTS"',
     'i18n_service.translate("report.by_departments", language).upper()'),
    
    # Table headers
    ('"Current SKU"',
     'i18n_service.translate("report.current_sku", language)'),
    
    ('"Target SKU"',
     'i18n_service.translate("report.target_sku", language)'),
    
    ('"Monthly Savings/User"',
     'i18n_service.translate("report.monthly_savings_per_user", language)'),
    
    ('"Annual Savings/User"',
     'i18n_service.translate("report.annual_savings_per_user", language)'),
    
    ('"User Count"',
     'i18n_service.translate("report.user_count", language)'),
    
    # Department summary
    ('"Department"',
     'i18n_service.translate("report.department", language).upper()'),
    
    ('"Current Cost"',
     'i18n_service.translate("report.current_cost", language)'),
    
    ('"Optimized Cost"',
     'i18n_service.translate("report.optimized_cost", language)'),
    
    ('"Annual Savings"',
     'i18n_service.translate("report.annual_savings_dept", language)'),
]

count = 0
for old, new in replacements:
    if old in content and 'i18n_service.translate' not in old:
        content = content.replace(old, new)
        count += 1

with open(file_path, 'w') as f:
    f.write(content)

print(f"✅ {count} textes remplacés dans pdf_generator.py")
PYEOF

echo ""
echo "🔄 Redémarrage du backend..."
docker-compose restart backend

echo ""
echo "⏳ Attente (10s)..."
sleep 10

echo ""
echo "✅ TOUTES LES CORRECTIONS ONT ÉTÉ APPLIQUÉES!"
echo ""
echo "📝 Résumé:"
echo "   ✅ Toutes les traductions ajoutées dans i18n_service.py"
echo "   ✅ Tous les textes en dur remplacés dans ExcelGenerator"
echo "   ✅ Tous les textes en dur remplacés dans PDFGenerator"
echo "   ✅ Backend redémarré"
echo ""
echo "🎯 TEST À EFFECTUER:"
echo ""
echo "1. Générez un rapport Excel"
echo "2. Ouvrez le fichier"
echo "3. Vérifiez que TOUS les champs sont en anglais:"
echo "   → Titres, en-têtes, labels, boutons"
echo "   → Symbole monétaire: $"
echo "   → Dates format: MM/DD/YYYY"
echo ""
echo "4. Répétez avec un PDF"
echo ""
echo "5. Si des champs sont encore en français:"
echo "   → Notez exactement lesquels"
echo "   → Envoyez-moi le fichier généré"
echo ""

# Sauvegarder le rapport des corrections
echo "📋 Rapport des corrections appliquées:" > /tmp/report_translations.log
echo "=======================================" >> /tmp/report_translations.log
echo "" >> /tmp/report_translations.log
echo "Date: $(date)" >> /tmp/report_translations.log
echo "Corrections ExcelGenerator: $(python3 -c \"print(open('backend/src/services/reports/excel_generator_simple.py').read().count('i18n_service.translate'))\")\" ) >> /tmp/report_translations.log
echo "Corrections PDFGenerator: $(python3 -c \"print(open('backend/src/services/reports/pdf_generator.py').read().count('i18n_service.translate'))\")\" ) >> /tmp/report_translations.log
echo "" >> /tmp/report_translations.log
echo "Backend redémarré: ✓" >> /tmp/report_translations.log

echo "✅ Rapport sauvegardé dans /tmp/report_translations.log"
echo ""
echo "🚀 Testez maintenant et envoyez-moi les fichiers générés si besoin!"
