#!/bin/bash

echo "🔧 CORRECTION COMPLETE: Tous les textes du PDF"
echo "=============================================="

cd "/mnt/d/DOC G/Projets/m365-license-optimizer"

# Étapes à effectuer manuellement après analyse

echo "📋 CORRECTIONS À APPLIQUER DANS:"
echo "   backend/src/services/reports/pdf_generator.py"
echo ""
echo "🎯 Liste des textes à remplacer:"
echo ""

# Liste complète des traductions
python3 << 'PYEOF'
# Traductions à ajouter
translations = {
    "en": {
        # Structure du PDF - Titres de sections
        "report.title.pdf_summary": "Microsoft 365 License Optimization Executive Summary",
        "report.generated_by": "Generated by",
        "report.on": "on",
        "report.tenant": "Tenant",
        "report.period": "Period",
        
        # Section KPI
        "report.total_monthly_cost": "Total Monthly Cost",
        "report.optimized_monthly_cost": "Optimized Monthly Cost", 
        "report.monthly_savings": "Monthly Savings",
        "report.annual_savings": "Annual Savings",
        "report.savings_rate": "Savings Rate",
        "report.total_users": "Total Users",
        "report.active_users": "Active Users",
        "report.total_licenses": "Total Licenses",
        
        # Sections
        "report.cost_analysis_overview": "Cost Analysis Overview",
        "report.user_license_analysis": "User License Analysis and Optimization",
        "report.license_distribution": "License Distribution",
        "report.key_findings": "Key Findings and Recommendations",
        "report.top_recommendations": "Top Recommendations by Savings",
        "report.by_departments": "Optimization Summary by Departments",
        "report.detailed_analysis": "Detailed License Analysis",
        "report.assumptions_notes": "Assumptions and Notes",
        
        # Table headers
        "report.user_principal_name": "User Principal Name",
        "report.display_name": "Display Name",
        "report.department": "Department",
        "report.job_title": "Job Title",
        "report.current_license": "Current License",
        "report.recommended_license": "Recommended License",
        "report.monthly_savings_per_user": "Monthly Savings/User",
        "report.annual_savings_per_user": "Annual Savings/User",
        "report.user_count": "User Count",
        "report.current_cost": "Current Cost",
        "report.optimized_cost": "Optimized Cost",
        "report.savings_potential": "Savings Potential",
        "report.exchange_usage_level": "Exchange Usage Level",
        "report.onedrive_usage": "OneDrive Usage",
        "report.teams_activity": "Teams Activity",
        "report.office_desktop_required": "Office Desktop Required",
        "report.last_activity_date": "Last Activity Date",
        "report.inactivity_days": "Inactivity Days",
        "report.recommendation_status": "Recommendation Status",
        "report.recommendation_reason": "Recommendation Reason",
        
        # Statuts
        "report.proposed": "Proposed",
        "report.validated": "Validated",
        "report.rejected": "Rejected",
        "report.sensitive": "Sensitive",
        "report.yes": "Yes",
        "report.no": "No",
    },
    "fr": {
        # Structure du PDF - Titres de sections
        "report.title.pdf_summary": "RAPPORT D'OPTIMISATION MICROSOFT 365",
        "report.generated_by": "Généré par",
        "report.on": "le",
        "report.tenant": "Tenant",
        "report.period": "Période",
        
        # Section KPI
        "report.total_monthly_cost": "Coût Mensuel Total",
        "report.optimized_monthly_cost": "Coût Mensuel Optimisé",
        "report.monthly_savings": "Économies Mensuelles",
        "report.annual_savings": "Économies Annuelles",
        "report.savings_rate": "Taux d'Économies",
        "report.total_users": "Nombre Total d'Utilisateurs",
        "report.active_users": "Utilisateurs Actifs",
        "report.total_licenses": "Nombre Total de Licences",
        
        # Sections
        "report.cost_analysis_overview": "Vue d'ensemble de l'analyse des coûts",
        "report.user_license_analysis": "Analyse des licences utilisateur et optimisation",
        "report.license_distribution": "Répartition des Licences",
        "report.key_findings": "Principales Conclusions et Recommandations",
        "report.top_recommendations": "Principales Recommandations par Économies",
        "report.by_departments": "Résumé par Départements",
        "report.detailed_analysis": "Analyse Détaillée des Licences",
        "report.assumptions_notes": "Hypothèses et Notes",
        
        # Table headers
        "report.user_principal_name": "Nom d'utilisateur principal",
        "report.display_name": "Nom d'affichage",
        "report.department": "Département",
        "report.job_title": "Titre du poste",
        "report.current_license": "Licence Actuelle",
        "report.recommended_license": "Licence Recommandée",
        "report.monthly_savings_per_user": "Économies Mensuelles/Utilisateur",
        "report.annual_savings_per_user": "Économies Annuelles/Utilisateur",
        "report.user_count": "Nombre d'utilisateurs",
        "report.current_cost": "Coût Actuel",
        "report.optimized_cost": "Coût Optimisé",
        "report.savings_potential": "Potentiel d'Économies",
        "report.exchange_usage_level": "Niveau d'utilisation Exchange",
        "report.onedrive_usage": "Utilisation OneDrive",
        "report.teams_activity": "Activité Teams",
        "report.office_desktop_required": "Bureau Office Requis",
        "report.last_activity_date": "Date dernière activité",
        "report.inactivity_days": "Jours d'inactivité",
        "report.recommendation_status": "Statut recommandation",
        "report.recommendation_reason": "Raison recommandation",
        
        # Statuts
        "report.proposed": "Proposé",
        "report.validated": "Validé",
        "report.rejected": "Rejeté",
        "report.sensitive": "Sensible",
        "report.yes": "Oui",
        "report.no": "Non",
    }
}

# Générer les commandes de correction
print("📋 TRADUCTIONS À AJOUTER DANS i18n_service.py:")
print("=" * 60)
for key in translations["en"]:
    print(f'"{key}": {{')
    print(f'  "en": "{translations["en"][key]}",')
    print(f'  "fr": "{translations["fr"][key]}",')
    print(f'}},')

print("")
print("📝 COMMANDES À EXÉCUTER DANS pdf_generator.py:")
print("=" * 60)
print("grep -n 'ws\\[' pdf_generator.py | grep -E '[A-ZÉ]'")
print("")
print("→ Pour chaque ligne trouvée, remplacer le texte français par:")
print("   i18n_service.translate('report.clé', language)")
print("")
print("🎯 Exemple concret:")
print('  Avant: ws["A5"] = "INDICATEURS CLÉS"')
print("  Après: ws['A5'] = i18n_service.translate('report.kpi_section', language).upper()")
print("")

PYEOF

# Créer le script de correction
python3 << 'PYEOF'
# Ce script sera généré automatiquement après analyse du PDF
print("✅ Script de correction généré")
PYEOF

echo ""
echo "🎉 PROCÉDURE COMPLETE:"
echo "======================"
echo ""
echo "1️⃣  Copiez les traductions ci-dessus dans i18n_service.py"
echo "    → Ajoutez-les dans les sections 'en' et 'fr'"
echo ""
echo "2️⃣  Ouvrez backend/src/services/reports/pdf_generator.py"
echo "    → Recherchez TOUS les textes entre guillemets avec accents"
echo "    → Remplacez chacun par la traduction correspondante"
echo ""
echo "3️⃣  Exemples de remplacement:"
echo '      - Avant: ws["A5"] = "INDICATEURS CLÉS"'
echo "      - Après:  ws['A5'] = i18n_service.translate('report.kpi_section', language).upper()"
echo ''
echo '      - Avant: ws["A7"] = "Coût actuel mensuel"'
echo "      - Après:  ws['A7'] = i18n_service.translate('report.current_monthly_cost', language)"
echo ""
echo "4️⃣  Redémarrez le backend:"
echo "    docker-compose restart backend"
echo ""
echo "5️⃣  Générez un nouveau PDF et vérifiez qu'il est entièrement en anglais"
echo ""
echo "📞 Si vous avez des doutes sur un texte spécifique:"
echo "    → Faites une capture d'écran du PDF"
echo "    → Notez le texte exact"
echo "    → Envoyez-la-moi pour traduction précise"
echo ""

echo "✅ CORRECTION COMPLEÈTE PRÊTE!"
