#!/bin/bash

# ============================================
# M365 License Optimizer - Quick Start Script
# ============================================
# This script automates the initial setup
# ============================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Banner
print_banner() {
    echo -e "${BLUE}"
    cat << "EOF"
    __  __ _____  __ _____   _     _                          
   |  \/  |___ / / /_| ____| | |   (_) ___ ___ _ __  ___  ___ 
   | |\/| | |_ \| '_ \___ \  | |   | |/ __/ _ \ '_ \/ __|/ _ \
   | |  | |___) | (_) |__) | | |___| | (_|  __/ | | \__ \  __/
   |_|  |_|____/ \___/____/  |_____|_|\___\___|_| |_|___/\___|
                                                                
    ___        _   _           _              
   / _ \ _ __ | |_(_)_ __ ___ (_)_______ _ __ 
  | | | | '_ \| __| | '_ ` _ \| |_  / _ \ '__|
  | |_| | |_) | |_| | | | | | | |/ /  __/ |   
   \___/| .__/ \__|_|_| |_| |_|_/___\___|_|   
        |_|                                    
EOF
    echo -e "${NC}"
    echo "Version 1.0 - Quick Start Setup"
    echo ""
}

# Check prerequisites
check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}✗ Docker not found. Please install Docker Desktop.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker found${NC}"
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        echo -e "${RED}✗ Docker Compose not found. Please install Docker Compose.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker Compose found${NC}"
    
    # Check Docker is running
    if ! docker info &> /dev/null; then
        echo -e "${RED}✗ Docker is not running. Please start Docker Desktop.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker is running${NC}"
    
    echo ""
}

# Setup environment file
setup_env() {
    echo -e "${YELLOW}Setting up environment variables...${NC}"
    
    if [ -f .env ]; then
        echo -e "${BLUE}ℹ .env file already exists${NC}"
        read -p "Do you want to overwrite it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Keeping existing .env file"
            return
        fi
    fi
    
    # Generate random passwords
    POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-20)
    REDIS_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-20)
    PGADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-20)
    
    cat > .env << EOF
# M365 License Optimizer - Environment Variables
# Generated by quick-start.sh on $(date)

# PostgreSQL Configuration
POSTGRES_DB=m365_optimizer
POSTGRES_USER=admin
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Redis Configuration
REDIS_PASSWORD=$REDIS_PASSWORD

# PgAdmin Configuration
PGADMIN_EMAIL=admin@m365optimizer.local
PGADMIN_PASSWORD=$PGADMIN_PASSWORD
EOF
    
    echo -e "${GREEN}✓ .env file created with secure random passwords${NC}"
    echo ""
    
    # Display credentials
    echo -e "${BLUE}==================================="
    echo "Generated Credentials"
    echo "===================================${NC}"
    echo "PostgreSQL:"
    echo "  Database: m365_optimizer"
    echo "  User: admin"
    echo "  Password: $POSTGRES_PASSWORD"
    echo ""
    echo "Redis:"
    echo "  Password: $REDIS_PASSWORD"
    echo ""
    echo "PgAdmin:"
    echo "  Email: admin@m365optimizer.local"
    echo "  Password: $PGADMIN_PASSWORD"
    echo ""
    echo -e "${YELLOW}⚠️  Save these credentials in a secure location!${NC}"
    echo ""
    
    read -p "Press Enter to continue..."
}

# Create directory structure
create_directories() {
    echo -e "${YELLOW}Creating directory structure...${NC}"
    
    mkdir -p docker/db
    mkdir -p scripts
    mkdir -p tests/mocks
    mkdir -p logs
    
    echo -e "${GREEN}✓ Directories created${NC}"
    echo ""
}

# Start services
start_services() {
    echo -e "${YELLOW}Starting Docker services...${NC}"
    echo "This may take a few minutes on first run..."
    echo ""
    
    docker-compose up -d
    
    echo ""
    echo -e "${GREEN}✓ Services started${NC}"
    echo ""
}

# Wait for services
wait_for_services() {
    echo -e "${YELLOW}Waiting for services to be ready...${NC}"
    
    # Wait for PostgreSQL
    echo -n "PostgreSQL: "
    for i in {1..30}; do
        if docker exec m365_optimizer_db pg_isready -U admin &> /dev/null; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        echo -n "."
        sleep 1
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
    done
    
    # Wait for Redis
    echo -n "Redis: "
    for i in {1..30}; do
        if docker exec m365_optimizer_redis redis-cli -a $REDIS_PASSWORD PING &> /dev/null; then
            echo -e "${GREEN}Ready${NC}"
            break
        fi
        echo -n "."
        sleep 1
        if [ $i -eq 30 ]; then
            echo -e "${RED}Timeout${NC}"
            exit 1
        fi
    done
    
    echo ""
}

# Run tests
run_tests() {
    echo -e "${YELLOW}Running infrastructure tests...${NC}"
    echo ""
    
    if [ -f scripts/test-infrastructure.sh ]; then
        chmod +x scripts/test-infrastructure.sh
        ./scripts/test-infrastructure.sh
    else
        echo -e "${YELLOW}⚠️  Test script not found, skipping tests${NC}"
    fi
}

# Print connection info
print_connection_info() {
    echo ""
    echo -e "${BLUE}==================================="
    echo "Connection Information"
    echo "===================================${NC}"
    echo ""
    echo "PostgreSQL:"
    echo "  Host: localhost"
    echo "  Port: 5432"
    echo "  Database: m365_optimizer"
    echo "  User: admin"
    echo "  Command: psql -h localhost -p 5432 -U admin -d m365_optimizer"
    echo ""
    echo "Redis:"
    echo "  Host: localhost"
    echo "  Port: 6379"
    echo "  Command: redis-cli -h localhost -p 6379 -a [password]"
    echo ""
    echo "PgAdmin (Web UI):"
    echo "  URL: http://localhost:5050"
    echo "  Email: admin@m365optimizer.local"
    echo ""
    echo -e "${YELLOW}Note: All passwords are stored in .env file${NC}"
    echo ""
}

# Print next steps
print_next_steps() {
    echo -e "${BLUE}==================================="
    echo "Next Steps"
    echo "===================================${NC}"
    echo ""
    echo "1. Access PgAdmin at http://localhost:5050"
    echo "2. Review the data in optimizer schema"
    echo "3. Proceed with Lot 2 (Backend API development)"
    echo ""
    echo "Useful commands:"
    echo "  • View logs: docker-compose logs -f"
    echo "  • Stop services: docker-compose down"
    echo "  • Restart services: docker-compose restart"
    echo "  • Run tests: ./scripts/test-infrastructure.sh"
    echo ""
    echo -e "${GREEN}✓ Setup complete!${NC}"
    echo ""
}

# Cleanup on error
cleanup() {
    if [ $? -ne 0 ]; then
        echo ""
        echo -e "${RED}Setup failed. Cleaning up...${NC}"
        docker-compose down &> /dev/null || true
        echo "Please check the error messages above and try again."
    fi
}

trap cleanup EXIT

# Main execution
main() {
    print_banner
    check_prerequisites
    create_directories
    setup_env
    start_services
    wait_for_services
    run_tests
    print_connection_info
    print_next_steps
}

# Run if not sourced
if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
    main
fi
